theme: jekyll-theme-minimal
title: Ольга Добрушина
logo: olgadobrushina.jpg
description: <b>Психолог, схема-терапевт, когнитивно-поведенческий психотерапевт, нейропсихолог. Кандидат медицинских наук.</b>

